# Generated by Django 4.2.22 on 2025-09-29 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import posthog.models.utils


class Migration(migrations.Migration):
    dependencies = [
        ("posthog", "0866_add_integration_to_batch_export_destination"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("llm_analytics", "0001_initial_migration"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvaluationConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=posthog.models.utils.UUIDT, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=400)),
                ("description", models.TextField(blank=True, default="")),
                ("enabled", models.BooleanField(default=True)),
                ("prompt", models.TextField()),
                ("conditions", models.JSONField(default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("team", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="posthog.team")),
            ],
            options={
                "ordering": ["-created_at", "id"],
                "indexes": [
                    models.Index(fields=["team", "-created_at", "id"], name="llm_analyti_team_id_8cf44c_idx"),
                    models.Index(fields=["team", "enabled"], name="llm_analyti_team_id_d75945_idx"),
                ],
            },
        ),
    ]
